---
abstract: 'Massively optimise your Perl OpenGL program with display lists'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.80
  Test::NoWarnings: 1.00
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: OpenGL::List
name: OpenGL-List
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/OpenGL-List
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/OpenGL-List
version: 0.01
